version: '3'

services:
  qrcode-rdbms:
    image: kartoza/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: pgpassword
      POSTGRES_DBNAME: qr_code
    volumes:
      - './.postgresql/:/var/lib/postgresql'
    ports:
      - '5432:5432'
  qrcode-api:
    build:
      context: .
      dockerfile: Dockerfile-Local
    environment:
      - GORM_HOST=qrcode-rdbms
    volumes:
      - './:/app'
    ports:
      - "8080:8000"